####### Main Settings #######
ctrl_rate:  100.0   # control loop rate [Hz]
first_jnt_idx: 4    # The index of first joint in the topic of "joint_states"
joint_num:     6    # number of axis

####### Settings for F/T sensor ######
wrench_filter_factor: 0.1   # T/tau
force_dead_zone:      2.0   # [N]
torque_dead_zone:     0.2   # [N*m]

####### Gains for Force Control ######
kp: 0.0
ki: 0.0
kd: 0.0

######## Admittance Parameters #######
mass:   [20,0,0,0,0,0,      # [kg]
         0,20,0,0,0,0,
         0,0,2,0,0,0,
         0,0,0,1000,0,0,
         0,0,0,0,1000,0,
         0,0,0,0,0,1000]

damping: [1000,0,0,0,0,0,    # [N*s/m]
          0,1000,0,0,0,0,
          0,0,100,0,0,0,
          0,0,0,1000,0,0,   # [N*s]
          0,0,0,0,1000,0,
          0,0,0,0,0,1000]

stiffness: [2000,0,0,0,0,0,    # [N/m]
            0,2000,0,0,0,0,
            0,0,0,0,0,0,
            0,0,0,10,0,0,    # [N*m/rad]
            0,0,0,0,10,0,
            0,0,0,0,0,10]

s_matrix: [1,0,0,0,0,0,     # select_matrix:
           0,1,0,0,0,0,     # 1->impedance control
           0,0,0,0,0,0,     # 0->force control
           0,0,0,1,0,0,
           0,0,0,0,1,0,
           0,0,0,0,0,1]

equilibrium_pose_spring: [0.000, 0.517, 0.370,    0.981, -0.195, 0.000, 0.000]

######### Other Parameters ########
workspace_limits: [-0.2, 0.2, 0.3, 0.7, -0.2, 0.5]  # [m]
arm_max_vel: 1.0    # [m/s]
arm_max_acc: 10.0   # [m/s^2]
