// Generated by gencpp from file force_control/SetFloat64Response.msg
// DO NOT EDIT!


#ifndef FORCE_CONTROL_MESSAGE_SETFLOAT64RESPONSE_H
#define FORCE_CONTROL_MESSAGE_SETFLOAT64RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace force_control
{
template <class ContainerAllocator>
struct SetFloat64Response_
{
  typedef SetFloat64Response_<ContainerAllocator> Type;

  SetFloat64Response_()
    : success(false)
    , message()  {
    }
  SetFloat64Response_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::force_control::SetFloat64Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::force_control::SetFloat64Response_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloat64Response_

typedef ::force_control::SetFloat64Response_<std::allocator<void> > SetFloat64Response;

typedef boost::shared_ptr< ::force_control::SetFloat64Response > SetFloat64ResponsePtr;
typedef boost::shared_ptr< ::force_control::SetFloat64Response const> SetFloat64ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::force_control::SetFloat64Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::force_control::SetFloat64Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::force_control::SetFloat64Response_<ContainerAllocator1> & lhs, const ::force_control::SetFloat64Response_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::force_control::SetFloat64Response_<ContainerAllocator1> & lhs, const ::force_control::SetFloat64Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace force_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::force_control::SetFloat64Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::force_control::SetFloat64Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::force_control::SetFloat64Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::force_control::SetFloat64Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::force_control::SetFloat64Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::force_control::SetFloat64Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::force_control::SetFloat64Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::force_control::SetFloat64Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::force_control::SetFloat64Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "force_control/SetFloat64Response";
  }

  static const char* value(const ::force_control::SetFloat64Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::force_control::SetFloat64Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::force_control::SetFloat64Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::force_control::SetFloat64Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloat64Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::force_control::SetFloat64Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::force_control::SetFloat64Response_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORCE_CONTROL_MESSAGE_SETFLOAT64RESPONSE_H
