// Generated by gencpp from file force_control/SetFloat64Request.msg
// DO NOT EDIT!


#ifndef FORCE_CONTROL_MESSAGE_SETFLOAT64REQUEST_H
#define FORCE_CONTROL_MESSAGE_SETFLOAT64REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace force_control
{
template <class ContainerAllocator>
struct SetFloat64Request_
{
  typedef SetFloat64Request_<ContainerAllocator> Type;

  SetFloat64Request_()
    : data(0.0)  {
    }
  SetFloat64Request_(const ContainerAllocator& _alloc)
    : data(0.0)  {
  (void)_alloc;
    }



   typedef double _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::force_control::SetFloat64Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::force_control::SetFloat64Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloat64Request_

typedef ::force_control::SetFloat64Request_<std::allocator<void> > SetFloat64Request;

typedef boost::shared_ptr< ::force_control::SetFloat64Request > SetFloat64RequestPtr;
typedef boost::shared_ptr< ::force_control::SetFloat64Request const> SetFloat64RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::force_control::SetFloat64Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::force_control::SetFloat64Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::force_control::SetFloat64Request_<ContainerAllocator1> & lhs, const ::force_control::SetFloat64Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::force_control::SetFloat64Request_<ContainerAllocator1> & lhs, const ::force_control::SetFloat64Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace force_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::force_control::SetFloat64Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::force_control::SetFloat64Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::force_control::SetFloat64Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::force_control::SetFloat64Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::force_control::SetFloat64Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::force_control::SetFloat64Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::force_control::SetFloat64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdb28210bfa9d7c91146260178d9a584";
  }

  static const char* value(const ::force_control::SetFloat64Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdb28210bfa9d7c9ULL;
  static const uint64_t static_value2 = 0x1146260178d9a584ULL;
};

template<class ContainerAllocator>
struct DataType< ::force_control::SetFloat64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "force_control/SetFloat64Request";
  }

  static const char* value(const ::force_control::SetFloat64Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::force_control::SetFloat64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 data\n"
;
  }

  static const char* value(const ::force_control::SetFloat64Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::force_control::SetFloat64Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloat64Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::force_control::SetFloat64Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::force_control::SetFloat64Request_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORCE_CONTROL_MESSAGE_SETFLOAT64REQUEST_H
