// Generated by gencpp from file force_control/SetString.msg
// DO NOT EDIT!


#ifndef FORCE_CONTROL_MESSAGE_SETSTRING_H
#define FORCE_CONTROL_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <force_control/SetStringRequest.h>
#include <force_control/SetStringResponse.h>


namespace force_control
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace force_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::force_control::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::force_control::SetString&) { return value(); }
};

template<>
struct DataType< ::force_control::SetString > {
  static const char* value()
  {
    return "force_control/SetString";
  }

  static const char* value(const ::force_control::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::force_control::SetStringRequest> should match
// service_traits::MD5Sum< ::force_control::SetString >
template<>
struct MD5Sum< ::force_control::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::force_control::SetString >::value();
  }
  static const char* value(const ::force_control::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::force_control::SetStringRequest> should match
// service_traits::DataType< ::force_control::SetString >
template<>
struct DataType< ::force_control::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::force_control::SetString >::value();
  }
  static const char* value(const ::force_control::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::force_control::SetStringResponse> should match
// service_traits::MD5Sum< ::force_control::SetString >
template<>
struct MD5Sum< ::force_control::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::force_control::SetString >::value();
  }
  static const char* value(const ::force_control::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::force_control::SetStringResponse> should match
// service_traits::DataType< ::force_control::SetString >
template<>
struct DataType< ::force_control::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::force_control::SetString >::value();
  }
  static const char* value(const ::force_control::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FORCE_CONTROL_MESSAGE_SETSTRING_H
